# Generated by Django 2.1.1 on 2018-09-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='заголовок', max_length=255),
        ),
    ]
